import { defineAction } from "@agent-native/core";
import { currentAccess } from "@agent-native/core/sharing";
import { writeAppState } from "@agent-native/core/application-state";
import { getDb, schema } from "../server/db/index.js";
import { eq, max } from "drizzle-orm";
import { nanoid } from "nanoid";
import { z } from "zod";
import { assertOwnFramework } from "../server/lib/curriculum-access.js";
import { generateCode } from "../shared/syllabus-import.js";

/**
 * Add an objective to a school's own syllabus library.
 *
 * For the page nobody could read the first time, and for the line a school
 * realises was missed. Without it the only way to add one was to import the
 * whole syllabus again.
 */
export default defineAction({
  description:
    "Add an objective to a syllabus this school imported — a line missed on first reading, or a page that could not be read then. Give the syllabus's own code where it has one; otherwise a code is generated and marked as the app's own.",
  schema: z.object({
    frameworkId: z
      .string()
      .describe("Which library entry, from get-school-library"),
    description: z.string().describe("What a learner will be able to do"),
    code: z.string().optional().describe("The syllabus's own code, if any"),
    strand: z.string().optional(),
    subStrand: z.string().optional(),
    gradeLevel: z.string().optional(),
    source: z.string().optional().describe("Document and page"),
  }),
  http: { method: "POST" },
  run: async (args) => {
    const { orgId } = currentAccess();
    if (!orgId) throw new Error("No school context.");
    const framework = await assertOwnFramework(args.frameworkId, orgId);
    const description = args.description.trim();
    if (!description) throw new Error("An objective cannot be empty.");
    const db = getDb();

    const [{ last }] = await db
      .select({ last: max(schema.frameworkObjectives.sequence) })
      .from(schema.frameworkObjectives)
      .where(eq(schema.frameworkObjectives.frameworkId, args.frameworkId));
    const sequence = (Number(last) || 0) + 1;

    const own = args.code?.trim();
    const code =
      own ||
      generateCode(framework.subject ?? framework.name, args.strand, sequence);
    const id = nanoid();
    await db.insert(schema.frameworkObjectives).values({
      id,
      frameworkId: args.frameworkId,
      code,
      strand: args.strand ?? null,
      subStrand: args.subStrand ?? null,
      subject: framework.subject ?? null,
      description,
      gradeLevel: args.gradeLevel ?? framework.gradeRange ?? null,
      sequence,
      sourceNote: args.source ?? null,
      codeGenerated: !own,
    });
    await writeAppState("refresh-signal", { ts: Date.now() });

    return {
      id,
      code,
      codeGenerated: !own,
      message: `Added to ${framework.name}${framework.subject ? ` · ${framework.subject}` : ""} as ${code}${own ? "" : " — a code generated by the app, not the syllabus's own"}.`,
    };
  },
});
